libros = [
    {
        "book_name": "Intel Galileo Networking Cookbook",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/1/1/1198os_intel20galileo20networking20cookbook.jpg",
        "author": "By Marco Schwartz",
        "page": 174.0,
        "release_date": "Aug 2015",
        "short_description": "Over 50 recipes that will help you use the Intel Galileo board to build exciting network-connected p...",
        "price": "$23.99",
        "programming_language": "C#",
        "concept": "Networking",
        "tool": "Galileo"
    },
    {
        "book_name": "OpenVPN Cookbook - Second Edition",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781786463128.png",
        "author": "By Jan Just Keijser",
        "page": 400.0,
        "release_date": "Feb 2017",
        "short_description": "Discover over 90 practical and exciting recipes that leverage the power of OpenVPN 2.4 to help you o...",
        "price": "$39.99",
        "programming_language": "C#",
        "concept": "Networking",
        "tool": "OpenVPN"
    },
    {
        "book_name": "Troubleshooting OpenVPN",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b05404.png",
        "author": "By Eric F Crist",
        "page": 178.0,
        "release_date": "Mar 2017",
        "short_description": "Get the solutions you need to troubleshoot any issue you may face to keep your OpenVPN up and runnin...",
        "price": "$27.99",
        "programming_language": "C#",
        "concept": "Networking",
        "tool": "OpenVPN"
    },
    {
        "book_name": "OpenVPN: Building and Integrating Virtual Private Networks",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/1/9/190481185x.jpg",
        "author": "By Markus Feilner",
        "page": 270.0,
        "release_date": "May 2006",
        "short_description": "Learn how to build secure VPNs using this powerful Open Source application",
        "price": "$35.99",
        "programming_language": "C#",
        "concept": "Networking",
        "tool": "OpenVPN"
    },
    {
        "book_name": "Kali Linux 2018: Assuring Security by Penetration Testing - Fourth Edition",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/c/o/cover_16.png",
        "author": "Shiva V. N Parasram",
        "page": 528.0,
        "release_date": "Oct 2018",
        "short_description": "Achieve the gold standard in penetration testing with Kali using this masterpiece, now in its fourth...",
        "price": 35.99,
        "programming_language": "C",
        "concept": "Penetration Testing",
        "tool": "Kali Linux"
    },
    {
        "book_name": "Learn Wireshark",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781789134506-original_29.png",
        "author": "Lisa Bock",
        "page": 432.0,
        "release_date": "Aug 2019",
        "short_description": "Grasp the basics of packet capture and analyze common protocols",
        "price": 27.99,
        "programming_language": "C",
        "concept": "Penetration Testing",
        "tool": "Wireshark"
    },
    {
        "book_name": "Mastering FreeSWITCH",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/8/8/8880os_3754_mastering20freeswitch.jpg",
        "author": "Anthony Minessale II",
        "page": 300.0,
        "release_date": "Jul 2016",
        "short_description": "Master the art of advanced VoIP and WebRTC communication with the most dynamic application server, F...",
        "price": 35.99,
        "programming_language": "C",
        "concept": "Real Time Communication",
        "tool": "FreeSWITCH"
    },
    {
        "book_name": "Mastering OpenLDAP: Configuring, Securing and Integrating Directory Services",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/1/8/1847191029.jpg",
        "author": "Matt Butcher",
        "page": 484.0,
        "release_date": "Aug 2007",
        "short_description": "If you want to go beyond the fundamentals of OpenLDAP, this is the guide you need. Starting with the...",
        "price": 29.99,
        "programming_language": "C",
        "concept": "Real Time Communication",
        "tool": "OpenLDAP"
    },
    {
        "book_name": "Amazon SimpleDB Developer Guide",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/7/3/7344en_mockupcover20template.jpg",
        "author": "By Prabhakar Chaganti",
        "page": 252.0,
        "release_date": "May 2010",
        "short_description": "Scale your application's database on the cloud using Amazon SimpleDB with this book and eBook",
        "price": "$23.99",
        "programming_language": "Java",
        "concept": "Database Programming",
        "tool": "Amazon SimpleDB"
    },
    {
        "book_name": "Android Application Development with Maven",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/0/1/0176_application20development20with20maven_cov_0.jpg",
        "author": "By Patroklos Papapetrou",
        "page": 192.0,
        "release_date": "Mar 2015",
        "short_description": "Learn how to use and configure Maven to support all phases of the development of an Android application",
        "price": "$23.99",
        "programming_language": "Java",
        "concept": "Android Development",
        "tool": "Maven"
    },
    {
        "book_name": "Android System Programming",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b06099.png",
        "author": "By Roger Ye",
        "page": 470.0,
        "release_date": "May 2017",
        "short_description": "Build, customize, and debug your own Android system",
        "price": "$35.99",
        "programming_language": "Java",
        "concept": "Android Development",
        "tool": "Android"
    },
    {
        "book_name": "Angular 2 By Example",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/7/1/7192os_5079_angular20220by20example.png",
        "author": "By Chandermani Arora",
        "page": 510.0,
        "release_date": "Nov 2016",
        "short_description": "Discover everything you need to know to build your own Angular 2 applications the hands-on way",
        "price": "$35.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "Angular"
    },
    {
        "book_name": "Angular 2 Components",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/2/3/2340os_b05076_angular20220components.png",
        "author": "By Nir Kaufman",
        "page": 124.0,
        "release_date": "Nov 2016",
        "short_description": "A quick and concise guide to Angular 2 Components",
        "price": "$23.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "Angular"
    },
    {
        "book_name": "Angular 6 by Example - Third Edition",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b09551_cover.png",
        "author": "By Chandermani Arora",
        "page": 504.0,
        "release_date": "Jun 2018",
        "short_description": "Harness the power of Angular Components, Router, Forms, Directives and much more to build professional...",
        "price": "$35.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "Angular"
    },
    {
        "book_name": "Angular Projects",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781838559359-original_96.jpeg",
        "author": "By Zama Khan Mohammed",
        "page": 350.0,
        "release_date": "Sep 2019",
        "short_description": "Understand Angular web development by building real-world captivating applications exploring various...",
        "price": "$27.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "Angular"
    },
    {
        "book_name": "Angular Services",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b05074.png",
        "author": "By Sohail Salehi",
        "page": 294.0,
        "release_date": "Feb 2017",
        "short_description": "Design state-of-the-art applications with customized Angular services",
        "price": "$31.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "Angular"
    },
    {
        "book_name": "Angular Test-Driven Development - Second Edition",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781786465474.png",
        "author": "By Md. Ziaul Haq",
        "page": 252.0,
        "release_date": "Feb 2017",
        "short_description": "Enhance your testing skills to build powerful and fault-free applications in Angular v4",
        "price": "$31.99",
        "programming_language": "JavaScript",
        "concept": "Application Testing",
        "tool": "Angular"
    },
    {
        "book_name": "AngularJS by Example",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b03520_cover.png",
        "author": "By Chandermani Arora",
        "page": 454.0,
        "release_date": "Mar 2015",
        "short_description": "Tackle the challenges of modern web development with this AngularJS tutorial, packed with practical ...",
        "price": "$24.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "Angular"
    },
    {
        "book_name": "AngularJS Deployment Essentials",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/3/5/3582os_b00110_angularjs20deployment20essentials.jpg",
        "author": "By Zachariah Moreno",
        "page": 148.0,
        "release_date": "Feb 2015",
        "short_description": "Learn how to optimally deploy your AngularJS applications to today's top hosting environments",
        "price": "$14.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "AngularJS"
    },
    {
        "book_name": "AngularJS Directives Cookbook",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b04051_cover.png",
        "author": "By Fernando Monteiro",
        "page": 206.0,
        "release_date": "Nov 2015",
        "short_description": "Extend the capabilities of AngularJS and build dynamic web applications by creating customized direc...",
        "price": "$31.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "Angular"
    },
    {
        "book_name": "AngularJS Directives",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/0/3/0339os.jpg",
        "author": "By Alex Vanston",
        "page": 110.0,
        "release_date": "Sep 2013",
        "short_description": "Intermediate JavaScript developers could take a big step forward with this essential step-by-step tu...",
        "price": "$19.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "AngularJS"
    },
    {
        "book_name": "AngularJS Essentials",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/0/0/0086os_angularjs20essentials_mini.jpg",
        "author": "By Rodrigo Branas",
        "page": 180.0,
        "release_date": "Aug 2014",
        "short_description": "Design and construct reusable, maintainable, and modular web applications with AngularJS.",
        "price": "$20.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "AngularJS"
    },
    {
        "book_name": "AngularJS Services",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/3/5/3568os_cov.jpg",
        "author": "By Jim Lavin",
        "page": 152.0,
        "release_date": "Aug 2014",
        "short_description": "Design, build, and test services to create a foundation for your AngularJS applications",
        "price": "$16.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "AngularJS"
    },
    {
        "book_name": "AngularJS Testing Cookbook",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/3/7/3742os.jpg",
        "author": "By Simon Bailey",
        "page": 180.0,
        "release_date": "Mar 2015",
        "short_description": "Eliminate volatile code by taking control and understanding how to test AngularJS applications",
        "price": "$23.99",
        "programming_language": "JavaScript",
        "concept": "Application Testing",
        "tool": "Angular"
    },
    {
        "book_name": "AngularJS Web Application Development Blueprints",
        "book_image": "www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/5/6/5617os_angularjs20web20application20development20blueprints_frontcover.jpg",
        "author": "By Vinci Rufus",
        "page": 300.0,
        "release_date": "Aug 2014",
        "short_description": "A practical guide to developing powerful web applications with AngularJS",
        "price": "$29.99",
        "programming_language": "JavaScript",
        "concept": "Front End Web Development",
        "tool": "AngularJS"
    },
    {
        'book_name': 'AngularJS: Maintaining Web Applications',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/a/n/angularjs_course20front20cover.jpg',
        'author': 'By Rodrigo Branas',
        'page': 1010.0,
        'release_date': 'Apr 2016',
        'short_description': 'Get started with speed building AngularJS applications, and scale up to a full-stack web application...',
        'price': '$59.99',
        'programming_language': 'JavaScript',
        'concept': 'Front End Web Development',
        'tool': 'Angular'
    },
    {
        'book_name': 'Appcelerator Titanium Business Application Development Cookbook',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/5/3/5343otcov.jpg',
        'author': 'By Benjamin Bahrenburg',
        'page': 328.0,
        'release_date': 'Jun 2013',
        'short_description': 'Over 40 hands-on recipes to quickly and efficiently create business grade Titanium Enterprise apps',
        'price': '$29.99',
        'programming_language': 'JavaScript',
        'concept': 'Cross Platform Mobile Development',
        'tool': 'Appcelerator Titanium'
    },
    {
        'book_name': 'Appcelerator Titanium Smartphone App Development Cookbook',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/3/9/3968exp_appcelerator20titanium20smartphone20app20developement20cookbook_frontcover.jpg',
        'author': 'By Boydlee Pollentine',
        'page': 308.0,
        'release_date': 'Dec 2011',
        'short_description': "You don't need to know Objective C or Java to create native apps for iPhone and Android. All you need...",
        'price': '$26.99',
        'programming_language': 'JavaScript',
        'concept': 'Cross Platform Mobile Development',
        'tool': 'Appcelerator Titanium'
    },
    {
        'book_name': 'Architecting Angular Applications with Redux, RxJS, and NgRx',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b07031_cover.png',
        'author': 'By Christoffer Noring',
        'page': 364.0,
        'release_date': 'Mar 2018',
        'short_description': 'Manage state in Angular to write high performing web apps by combining the power of Flux, RxJS, and ...',
        'price': '$35.99',
        'programming_language': 'JavaScript',
        'concept': 'Front End Web Development',
        'tool': 'Angular'
    },
    {
        'book_name': 'Arduino Robotic Projects',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/8/9829os.jpg',
        'author': 'By Dr. Richard Grimmett',
        'page': 240.0,
        'release_date': 'Aug 2014',
        'short_description': 'Build awesome and complex robots with the power of Arduino.',
        'price': '$26.99',
        'programming_language': 'C',
        'concept': 'Single Board Computers',
        'tool': 'Arduino'
    },
    {
        'book_name': 'Arduino Robotic Projects',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/8/9829os.jpg',
        'author': 'By Dr. Richard Grimmett',
        'page': 240.0,
        'release_date': 'Aug 2014',
        'short_description': 'Build awesome and complex robots with the power of Arduino.',
        'price': '$26.99',
        'programming_language': 'C++',
        'concept': 'Single Board Computers',
        'tool': 'Arduino'
    },
     {
        'book_name': 'Artificial Intelligence with Python - Second Edition',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781839219535-original_2.jpg',
        'author': 'By Alberto Artasanchez',
        'page': 618.0,
        'release_date': 'Jan 2020',
        'short_description': 'New edition of the bestselling guide to artificial intelligence with Python, updated to Python 3.x a...',
        'price': '$34.99',
        'programming_language': 'Python',
        'concept': 'Artificial Intelligence',
        'tool': 'TensorFlow'
    },
    {
        'book_name': 'Backbone.js Blueprints',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/6/9/6997os.jpg',
        'author': 'By Andrew Burgess',
        'page': 256.0,
        'release_date': 'May 2014',
        'short_description': 'Everything you need to know about building front end apps in Backbone.js is contained in this book. ...',
        'price': '$29.99',
        'programming_language': 'JavaScript',
        'concept': 'Front End Web Development',
        'tool': 'Backbone.js'
    },
    {
        'book_name': 'Backbone.js Cookbook',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/2/7/2728os_cov.jpg',
        'author': 'By Vadim Mirgorod',
        'page': 282.0,
        'release_date': 'Aug 2013',
        'short_description': 'For JavaScript developers the Backbone.js framework is full of potential. This book, with its access...',
        'price': '$26.99',
        'programming_language': 'JavaScript',
        'concept': 'Front End Web Development',
        'tool': 'Backbone.js'
    },
    {
        'book_name': 'Backbone.js Essentials',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/4/7/4790os_backbone.js20essentials.jpg',
        'author': 'By Jeremy Walker',
        'page': 180.0,
        'release_date': 'May 2015',
        'short_description': 'Build amazing high-performance web applications using Backbone.js',
        'price': '$19.99',
        'programming_language': 'JavaScript',
        'concept': 'Front End Web Development',
        'tool': 'Backbone.js'
    },
    {
        'book_name': 'Become a Python Data Analyst',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781789531701-original_32.png',
        'author': 'By Alvaro Fuentes',
        'page': 178.0,
        'release_date': 'Aug 2018',
        'short_description': 'Enhance your data analysis and predictive modeling skills using popular Python tools',
        'price': '$16.99',
        'programming_language': 'Python',
        'concept': 'Data Analysis',
        'tool': 'Scikit-learn'
    },
    {
        'book_name': 'Big Data Analytics with R and Hadoop',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/3/2/3282os.jpg',
        'author': 'By Vignesh Prajapati',
        'page': 238.0,
        'release_date': 'Nov 2013',
        'short_description': 'If you’re an R developer looking to harness the power of big data analytics with Hadoop, then this b...',
        'price': '$29.99',
        'programming_language': 'R',
        'concept': 'Big Data',
        'tool': 'Hadoop'
    },
    {
        'book_name': 'Big Data Visualization',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/b/0/b04671.png',
        'author': 'By James D. Miller',
        'page': 304.0,
        'release_date': 'Feb 2017',
        'short_description': 'Learn effective tools and techniques to separate big data into manageable and logical components for...',
        'price': '$35.99',
        'programming_language': 'R',
        'concept': 'Big Data',
        'tool': 'D3'
    },
    {
        'book_name': 'Build Applications with Meteor',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781787129887.png',
        'author': 'By Dobrin Ganev',
        'page': 388.0,
        'release_date': 'May 2017',
        'short_description': 'Build a variety of cross-platform applications with the world’s most complete full-stack JavaScript ...',
        'price': '$35.99',
        'programming_language': 'JavaScript',
        'concept': 'Server Side Web Development',
        'tool': 'Meteor'
    },
    {
        'book_name': 'Building Cross-Platform Desktop Applications with Electron',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781786464125.png',
        'author': 'By Muhammed Jasim',
        'page': 344.0,
        'release_date': 'Apr 2017',
        'short_description': 'Learn how to develop cross-platform desktop app from scratch with Electron and Node',
        'price': '$35.99',
        'programming_language': 'JavaScript',
        'concept': 'Cross Platform Mobile Development',
        'tool': 'Electron'
    },
    {
        'book_name': 'Building Modern Web Applications Using Angular 4',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/9/7/9781785880728.png',
        'author': 'By Shravan Kumar Kasagoni',
        'page': 226.0,
        'release_date': 'May 2017',
        'short_description': 'Design and develop next generation web applications using Angular 2 and Angular 4',
        'price': '$31.99',
        'programming_language': 'JavaScript',
        'concept': 'Front End Web Development',
        'tool': 'Angular'
    },
    {
        'book_name': 'C Programming for Arduino',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/7/5/7584os_cover.jpg',
        'author': 'By Julien Bayle',
        'page': 512.0,
        'release_date': 'May 2013',
        'short_description': 'Building your own electronic devices is fascinating fun and this book helps you enter the world of a...',
        'price': '$29.99',
        'programming_language': 'C++',
        'concept': 'Single Board Computers',
        'tool': 'Arduino'
    },
    {
        'book_name': 'C Programming for Arduino',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/7/5/7584os_cover.jpg',
        'author': 'By Julien Bayle',
        'page': 512.0,
        'release_date': 'May 2013',
        'short_description': 'Building your own electronic devices is fascinating fun and this book helps you enter the world of a...',
        'price': '$29.99',
        'programming_language': 'C',
        'concept': 'Single Board Computers',
        'tool': 'Arduino'
    },
    {
        'book_name': 'C Programming for Arduino',
        'book_image': 'www.packtpub.com/media/catalog/product/cache/5d165500a520a389deb95b325792ea25/7/5/7584os_cover.jpg',
        'author': 'By Julien Bayle',
        'page': 512.0,
        'release_date': 'May 2013',
        'short_description': 'Building your own electronic devices is fascinating fun and this book helps you enter the world of a...',
        'price': '$29.99',
        'programming_language': 'C',
        'concept': 'Single Board Computers',
        'tool': 'Arduino'
    }
]

'''for libro in libros:
    print("Título:", libro["book_name"])
    print("Imagen:", libro["book_image"])
    print("Autor:", libro["author"])
    print("Páginas:", libro["page"])
    print("Fecha de lanzamiento:", libro["release_date"])
    print("Descripción:", libro["short_description"])
    print("Precio:", libro["price"])
    print("Lenguaje de programación:", libro["programming_language"])
    print("Concepto:", libro["concept"])
    print("Herramienta:", libro["tool"])
    print("---------------------------------")'''
